"""add_weekly_reports_table

Revision ID: 183f071a1dd9
Revises: cb46d96041c7
Create Date: 2026-02-19 13:38:04.863128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '183f071a1dd9'
down_revision: Union[str, None] = 'cb46d96041c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('attendance_count', sa.Integer(), nullable=False),
    sa.Column('absent_count', sa.Integer(), nullable=False),
    sa.Column('late_count', sa.Integer(), nullable=False),
    sa.Column('homework_completed', sa.Integer(), nullable=False),
    sa.Column('homework_total', sa.Integer(), nullable=False),
    sa.Column('ai_report', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_reports')
    # ### end Alembic commands ###
