"""Add description to subjects and fix group relationships

Revision ID: b5fe43419586
Revises: c70c0cf5657e
Create Date: 2026-02-13 23:22:48.385602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5fe43419586'
down_revision: Union[str, None] = 'c70c0cf5657e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'description')
    # ### end Alembic commands ###
